name: compile

run-name: compile stage

on: [push, pull_request]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install static analysis tools
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: run static analysis
        run: |
          cppcheck --enable-all --error-exitcode=1 --inline-suppr --force --quiet .

      - name: setup arduino cli
        uses: arduino/setup-arduino-cli@v2

      - name: configure esp board url
        run: |
          arduino-cli config init --overwrite
          arduino-cli config set board_manager.additional_urls https://espressif.github.io/arduino-esp32/package_esp32_index.json


      - name: install esp board
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: compile and verify syntax
        run: |
          arduino-cli compile \
          --fqbn esp32:esp32:esp32 \
          --warnings all \
          --build-property "compiler.c.extra_flags=-Werror" \
          --build-property "compiler.cpp.extra_flags=-Werror" \
          --verbose \
          .
